# Generated by Django 4.2.6 on 2023-10-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_product_multipleaddress_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='multipleaddress',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.vendor'),
        ),
    ]
