# Generated by Django 4.2.6 on 2023-11-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_vendor_has_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
