# Generated by Django 4.2.6 on 2023-10-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='image',
        ),
    ]
