# Generated by Django 4.2.6 on 2023-10-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_wishlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Customer',
            new_name='customer',
        ),
    ]
