# Generated by Django 4.2.6 on 2023-11-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_order_quantity_order_amount_order_has_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercancel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordercancel',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderCancel',
        ),
    ]
