# Generated by Django 4.2.6 on 2023-11-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
