# Generated by Django 4.2.6 on 2023-11-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_orderdetail_stripe_payment_intent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
