# Generated by Django 4.2.6 on 2023-11-01 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_wishlist_image'),
        ('payment', '0004_delete_orderdetail_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Out for Delevery', 'Out for Delevery'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
        ),
    ]
