# Generated by Django 4.2.6 on 2023-11-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
