# Generated by Django 4.2.6 on 2023-11-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_wishlist_image'),
        ('customer', '0005_vendor_has_approved'),
        ('payment', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasion', models.CharField(choices=[('EXD', 'Expected delivery date has changed and the product is arriving at a later date.'), ('PRA.', 'Product is not required anymore.'), ('change my mind', 'Change My Mind'), ('BR', 'Bad review from friends/relatives after ordering the product.')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
