# Generated by Django 4.2.6 on 2023-11-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_cancelorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Out for Delevery', 'Out for Delevery'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Placed', max_length=30),
        ),
    ]
