# Generated by Django 4.2.6 on 2023-11-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_orderdetail_status'),
        ('ratting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratting',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.orderdetail'),
        ),
    ]
